---
- name: creating user
  hosts: jenkins
  gather_facts: no
  become: true
  tasks:
  - name: create a file in remote server
    file:
      path: /opt/aatmanni.txt
      state: touch
      owner: root
      group: root
      mode: 0755
